export enum Screens {
  MAIN_APP = 'MAIN_APP',
  
  SPLASH_MAIN = 'SPLASH_MAIN',

  AUTH_START = 'AUTH_START',
  AUTH_CODE = 'AUTH_CODE',
  AUTH_REGISTER_CRIDENTIALS = 'AUTH_REGISTER_CRIDENTIALS',
  AUTH_REGISTER_PROFILE = 'AUTH_REGISTER_PROFILE',

  SCAN_MAIN = 'LOOKS_MAIN',

  CATALOG_MAIN = 'CATALOG_MAIN',

  LOOKS_MAIN = 'LOOKS_MAIN',
  LOOKS_DETAIL = 'LOOKS_DETAIL',
  
  FAVORITES_MAIN = 'FAVORITES_MAIN',
  
  PROFILE_MAIN = 'PROFILE_MAIN',
}
